//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanielWillett.SpeedBytes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanielWillett.SpeedBytes.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given {0} array is too long to be written by the called method ({1} elements). The max length is {2} elements..
        /// </summary>
        internal static string ArrayTooLongToWrite {
            get {
                return ResourceManager.GetString("ArrayTooLongToWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic argument {0} is not able to be read/written automatically..
        /// </summary>
        internal static string AutoEncodeTypeNotFoundExceptionWithTypeName {
            get {
                return ResourceManager.GetString("AutoEncodeTypeNotFoundExceptionWithTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByteReader tried to read past its buffer..
        /// </summary>
        internal static string ByteBufferOverflowException {
            get {
                return ResourceManager.GetString("ByteBufferOverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to create an auto-encoder method. See inner exception for details..
        /// </summary>
        internal static string CouldNotCreateEncoderMethod {
            get {
                return ResourceManager.GetString("CouldNotCreateEncoderMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the elements in the array is null..
        /// </summary>
        internal static string ElementInArrayIsNull {
            get {
                return ResourceManager.GetString("ElementInArrayIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream can not read..
        /// </summary>
        internal static string GivenStreamCanNotRead {
            get {
                return ResourceManager.GetString("GivenStreamCanNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream can not write..
        /// </summary>
        internal static string GivenStreamCanNotWrite {
            get {
                return ResourceManager.GetString("GivenStreamCanNotWrite", resourceCulture);
            }
        }
    }
}
